### ISSUE TITLE
unable to produce simulated target exome data

### ISSUE THREAD

**Issue by ZKai0801** [NabaviLab/CNV_Project#6]
Hi,

I tried to use CNV-sim to produce simulated data for both whole genome and targeted exome. When I ran simulation on whole genome, the software worked fine. However, when I tried to run simulation on targeted exome, I got following error message:

```
[kai@admin simulated_data]$ python2 ~/softwares/CNV-Sim/cnv-sim.py exome ~/human_chr/chr17.fa DF_chr17.bed -o DF_chr17 -l 150
[CNV SIM 2019-01-09 09:04:47] simulation type: targeted exome sequencing
[CNV SIM 2019-01-09 09:04:48] loading genome file ..
[CNV SIM 2019-01-09 09:04:48] successfully loaded a genome of length 81195210
[CNV SIM 2019-01-09 09:04:48] loading target file ..
[CNV SIM 2019-01-09 09:04:48] sorting and merging targets ..
Traceback (most recent call last):
  File "/public/home/kai/softwares/CNV-Sim/cnv-sim.py", line 106, in <module>
    main()
  File "/public/home/kai/softwares/CNV-Sim/cnv-sim.py", line 102, in main
    simulate_exome_cnv(simulation_parameters, cnv_list_parameters)
  File "/public/home/kai/softwares/CNV-Sim/cnvsim/exome_simulator.py", line 235, in simulate_exome_cnv
    target_file = fileio.prepareTargetFile(target_file)
  File "/public/home/kai/softwares/CNV-Sim/cnvsim/fileio.py", line 53, in prepareTargetFile
    subprocess.call(["bedtools", "merge", "-i", sorted_file], stdout=f)
  File "/public/software/python2.7.15/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/public/software/python2.7.15/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/public/software/python2.7.15/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory 
```

I would be very appreciated if you can help me with this issue.

**Comment by abdelrahmanhosny** [comment]
Hello,
It looks like you don’t have bedtools installed. Did you install all the requirements as per the installation guide?

Abdelrahman

________________________________

**Comment by ZKai0801** [comment]
Argh, you are right. I didn't notice I haven't got bedtools installed on my current server...
Thanks for your time!
